parameters:
  cors.config:
    enabled: true
    allowedHeaders:
      - authorization
      - content-type
      - x-csrf-token
      - commerce-cart-token
    allowedMethods:
      - GET
      - POST
      - PATCH
      - DELETE
      - OPTIONS
    allowedOrigins:
      - 'http://localhost'
      - 'http://localhost:3001'
      - 'https://localhost'
      - 'https://rareimagery.net'
      - 'https://www.rareimagery.net'
    exposedHeaders:
      - commerce-cart-token
    maxAge: 3600
    supportsCredentials: true
